import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next"
import { Atkinson_Hyperlegible_Next } from "next/font/google";
import "./globals.css";

const atkinson = Atkinson_Hyperlegible_Next({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "700"],
  variable: "--font-atkinson",
})

export const metadata: Metadata = {
  title: "Radar Parlamentar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className={`h-full antialiased`}
    >
      <body className={`${atkinson.variable} min-h-full flex flex-col`}>{children}</body>
      <Analytics />
    </html>
  );
}
